# Site Settings
title: Dennis Houlihan
description: Physicist, Data Scientist, and Quant Enthusiast
url: https://djhoulihan.github.io
baseurl: ""

# Author Info
author:
  name: Dennis Houlihan
  email: dennishoulihan12@gmail.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
